import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import productImage from '../assets/images/image-product-desktop.jpg'
import cartIcon from '../assets/images/icon-cart.svg'


export default function Home() {
// const ImageLoader = ({src, width, quality, alt}) =>  {
//   return `${src}?w=${width}&q=${quality || 75}&alt=${alt}`
// }

  return (
    <div className={styles.wrapper}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.primaryContainer}>
        <Image 
        className={styles.productImage}
          src={productImage}
          alt='image product'
          width={300}
          height={450}
        />
        <div className={styles.overview}>
          <h5 className={styles.perfume}>Perfume</h5>
          <h1 className={styles.perfumeName}>Gabriel Essence Eau de Parfum</h1>
          <p className={styles.perfumeDesc}>A floral, solar and voluptuous interpretation composed by Oliver Porge, Perfumer-creator for the house of CHANEL</p>
          <div className={styles.priceWrapper}>
            <h1 className={styles.perfumePrice}>$149,99</h1>
            <p className={styles.perfumeoldPrice}>$169,99</p>
          </div>
          <button className={styles.add}>
            <Image 
            src={cartIcon}
            alt='cart Icon'
            />
            Add to Cart</button>

        </div>
       
      </div>
    </div>
  )
}
